/*
 * CodeGenAndTransformerAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CodeGenAndTransformerAPI.PCL;
using CodeGenAndTransformerAPI.PCL.Utilities;

namespace CodeGenAndTransformerAPI.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum FormatTransformer
    {
        APIMATIC, //TODO: Write general description for this method
        WADL2009, //TODO: Write general description for this method
        SWAGGER10, //TODO: Write general description for this method
        SWAGGER20, //TODO: Write general description for this method
        SWAGGERYAML, //TODO: Write general description for this method
        APIBLUEPRINT, //TODO: Write general description for this method
        RAML, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type FormatTransformer
    /// </summary>
    public static class FormatTransformerHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "apimatic", "wadl2009", "swagger10", "swagger20", "swaggeryaml", "apiblueprint", "raml" };

        /// <summary>
        /// Converts a FormatTransformer value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The FormatTransformer value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(FormatTransformer enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case FormatTransformer.APIMATIC:
                case FormatTransformer.WADL2009:
                case FormatTransformer.SWAGGER10:
                case FormatTransformer.SWAGGER20:
                case FormatTransformer.SWAGGERYAML:
                case FormatTransformer.APIBLUEPRINT:
                case FormatTransformer.RAML:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of FormatTransformer values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of FormatTransformer values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<FormatTransformer> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into FormatTransformer value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed FormatTransformer value</returns>
        public static FormatTransformer ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type FormatTransformer", value));

            return (FormatTransformer) index;
        }
    }
} 