/*
 * CodeGenAndTransformerAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using CodeGenAndTransformerAPI.PCL.Controllers;
using CodeGenAndTransformerAPI.PCL.Http.Client;
using CodeGenAndTransformerAPI.PCL.Utilities;

namespace CodeGenAndTransformerAPI.PCL
{
    public partial class CodeGenAndTransformerAPIClient
    {

        /// <summary>
        /// Singleton access to CodeGeneration controller
        /// </summary>
        public CodeGenerationController CodeGeneration
        {
            get
            {
                return CodeGenerationController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to APIDescriptionValidation controller
        /// </summary>
        public APIDescriptionValidationController APIDescriptionValidation
        {
            get
            {
                return APIDescriptionValidationController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to APITransformer controller
        /// </summary>
        public APITransformerController APITransformer
        {
            get
            {
                return APITransformerController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public CodeGenAndTransformerAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public CodeGenAndTransformerAPIClient(string basicAuthUserName, string basicAuthPassword)
        {
            Configuration.BasicAuthUserName = basicAuthUserName;
            Configuration.BasicAuthPassword = basicAuthPassword;
        }
        #endregion
    }
}